### ISSUE TITLE
Error con node-gyp en MAC M1 con OS Ventura 13.2

### ISSUE THREAD

**Issue by flaa1986** [TIPS-SA/facturacionelectronicapy-kude#1]
```
npm i facturacionelectronicapy-kude

> nodejs-java@1.0.16 install /Users/MYUSER/node_proyects/sifen/node_modules/nodejs-java
> node-gyp rebuild

awk: syntax error at source line 1
 context is
         >>> Studio. <<< app/Contents/jre/Contents/Home
awk: bailing out at source line 1
gyp: Call to 'awk -F/ -v h=`node findJavaHome.js` 'BEGIN {n=split(h, a); print a[2]; exit}'' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/MYUSER/.nvm/versions/node/v14.21.1/lib/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/MYUSER/.nvm/versions/node/v14.21.1/bin/node" "/Users/MYUSER/.nvm/versions/node/v14.21.1/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/MYUSER/node_proyects/sifen/node_modules/nodejs-java
gyp ERR! node -v v14.21.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-java@1.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-java@1.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MYUSER/.npm/_logs/2023-03-13T19_09_42_127Z-debug.log```

**Comment by flaa1986** [comment]
@marcosjara por si acaso te sucedió este error en algún momento.
Ya confirmé que tambien ocurre en macs anteriores a la M1
